version: "3.5"

services:
  postgres:
      image: postgres:latest
      environment:
        - POSTGRES_USER=strapi
        - POSTGRES_PASSWORD=strapi
        - POSTGRES_DB=strapi
      volumes:
        - ./volumes/postgres:/var/lib/postgresql/data
      ports:
        - "5432:5432"
  grafana:
    image: grafana/grafana:latest
    network_mode: "bridge"
    container_name: grafana
    volumes:
      - ./volumes/grafana:/var/lib/grafana
    ports:
      - "3000:3000"
    restart: always
    environment:
      - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
  app:
    build:
      context: .
      dockerfile: ./app.dockerfile
    volumes:
      - .:/home/app
      - .:/home/app/node_modules
  api:
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    environment:
      KEY: 'replace-with-random-value'
      SECRET: 'replace-with-random-value'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'd1r3ctu5'
      WEBSOCKETS_ENABLED: true
  