version: "3.5"

services:
  postgres:
      container_name: "database"
      image: postgres:latest
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=placement_website_gct
      volumes:
        - ./volumes/postgres:/var/lib/postgresql/data
      ports:
        - '5432:5432'
  # grafana:
  #   image: grafana/grafana:latest
  #   depends_on:
  #     - postgres
  #   network_mode: "bridge"
  #   container_name: grafana
  #   volumes:
  #     - ./volumes/grafana:/var/lib/grafana
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   environment:
  #     - GF_INSTALL_PLUGINS=marcusolsson-json-datasource
  # app:
  #   build:
  #     context: .
  #     dockerfile: ./app.dockerfile
  #   volumes:
  #     - .:/home/app
  #     - .:/home/app/node_modules
  api:
    container_name: api
    ports:
      - "8055:8055"
    build: 
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api/snapshots:/home/api/snapshots
    environment:
      - DB_HOST=postgres
  server:
    image: nginx
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    environment:
    - NGINX_HOST=foobar.com
    - NGINX_PORT=80
  
  